In [1]:
import numpy as np

In [3]:
lista = [1, 2, 3, 4, 5]
array = np.array(lista)

In [4]:
print(type(lista))
print(type(array))

<class 'list'>
<class 'numpy.ndarray'>


In [5]:
zeros = np.zeros(10)
print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
array[0] = 9
print(array)

[9 2 3 4 5]


In [7]:
mat = np.zeros((5, 3))
print(mat)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
notas = [9.8, 5.6, 7.8, 9.1, 6.5]
notas = np.array(notas)

In [9]:
print(notas.max())
print(notas.min())
print(notas.std())
print(notas.mean())

9.8
5.6
1.5628179676469045
7.76


In [10]:
print(notas.argmin())

1


In [11]:
def summarize(notas):
    array = np.array(notas)
    min = array.min()
    mean = array.mean()
    max = array.max()
    std = array.std()

    msg = f'Medidade de resumo Mínimo: {min} \n Máxima: {max} \n Média: {mean} \n Desvio-Padrão: {std}'

    return msg

In [12]:
summarize([9, 7, 6, 8, 10])

'Medidade de resumo Mínimo: 6 \n Máxima: 10 \n Média: 8.0 \n Desvio-Padrão: 1.4142135623730951'

In [18]:
is_covid = np.array([1, 0, 0, 1, 1, 0])

In [19]:
mask = (is_covid == 1)
mask

array([ True, False, False,  True,  True, False])

In [20]:
is_covid[mask]

array([1, 1, 1])

In [30]:
notas = [9.8, 5.6, 7.8, 9.1, 6.5]
notas = np.array(notas)
mask = (notas < 7) | (notas > 9)
notas[mask]

array([9.8, 5.6, 9.1, 6.5])

In [29]:
(notas < 7) | (notas > 9)

array([ True,  True, False,  True,  True])