In [1]:
import numpy as np

# Matrizes

In [2]:
mat_A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
mat_A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
mat_A[0]

array([1, 2, 3])

In [5]:
#matriz transposta 
mat_A.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [6]:
mat_A + mat_A.T

array([[ 2,  6, 10],
       [ 6, 10, 14],
       [10, 14, 18]])

In [7]:
#multiplicação de matrizes
np.dot(mat_A, mat_A.T)

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

In [10]:
mat_A = np.array([[1, 1, -3], [2, 1, 3], [2, 0, -1]])

In [11]:
#determinante
print(np.linalg.det(mat_A))
print(np.linalg.det(mat_A.T))

13.0
13.0


In [12]:
#inversa
np.linalg.inv(mat_A)

array([[-0.07692308,  0.07692308,  0.46153846],
       [ 0.61538462,  0.38461538, -0.69230769],
       [-0.15384615,  0.15384615, -0.07692308]])

In [13]:
np.dot(mat_A, np.linalg.inv(mat_A))

array([[ 1.00000000e+00, -5.55111512e-17,  5.55111512e-17],
       [ 0.00000000e+00,  1.00000000e+00,  5.55111512e-17],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [14]:
#matriz identidade
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Sistemas Lineares

$x = A^{-1}b$

In [16]:
A = np.array([[1, 2, 3], [2, 3, 3], [1, 2, 0]])
b = np.array([1, -3, 6])

In [18]:
np.dot(np.linalg.inv(A), b)

array([-14.        ,  10.        ,  -1.66666667])

In [19]:
np.linalg.solve(A, b)

array([-14.        ,  10.        ,  -1.66666667])

# Transformações Lineares